name: github-contribution-snake

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # mise à jour tous les jours à minuit UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate contribution snake
        uses: platane/snk@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./github-contribution-grid-snake.svg
